### ISSUE TITLE
Tensorboard refuses to reveal itself from docker

### ISSUE THREAD

**Issue by fabiansd** [acntech/RoboSchool#7]
When i start tensorboard on an exposed port (e.g. 6006) through localhost it will not show up in the browser even though it should according to its documentations. it is possible to run it locally though

**Comment by kristiansvalland** [comment]
Hi, I have had this problem myself with docker and inside a vagrant box.
By running 
`tensorboard --logdir runs`
instead of
`tensorboard --logdir runs --host localhost`
I get the expected result by going to localhost:6006.
This is done with the "rl-env" and not "rl-env-p37".
I don't know if this is a ubuntu-related fix or solves the problem in general. I am not that familiar with docker.
